package com.stano.schema.gensql.impl.h2;

import com.stano.schema.gensql.impl.common.OutputMode;
import com.stano.schema.gensql.impl.common.SQLGenerator;
import com.stano.schema.gensql.impl.common.SQLGeneratorOptions;
import com.stano.schema.model.BooleanMode;
import com.stano.schema.model.Column;
import com.stano.schema.model.ColumnType;
import com.stano.schema.model.DatabaseType;
import com.stano.schema.model.EnumType;
import com.stano.schema.model.EnumValue;
import com.stano.schema.model.ForeignKeyMode;
import com.stano.schema.model.Schema;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.assertEquals;

@DisplayName("H2 column type SQL generation")
class H2ColumnTypeGeneratorTest {

  private H2ColumnTypeGenerator generator;

  @BeforeEach
  void setUp() {
    generator = createGenerator(BooleanMode.NATIVE, null);
  }

  @ParameterizedTest(name = "{0} -> {1}")
  @DisplayName("simple types should map to expected SQL")
  @CsvSource({
    "SEQUENCE,    integer generated by default as identity (start with 1)",
    "LONGSEQUENCE, bigint generated by default as identity (start with 1)",
    "BYTE,        tinyint",
    "SHORT,       smallint",
    "INT,         integer",
    "LONG,        bigint",
    "FLOAT,       real",
    "DOUBLE,      double precision",
    "DATE,        date",
    "DATETIME,    timestamp",
    "TIMESTAMP,   timestamp",
    "TIME,        time",
    "TIMESTAMPTZ, timestamp with time zone",
    "UUID,        uuid",
    "BINARY,      binary large object",
    "JSON,        character large object",
    "CITEXT,      character large object",
    "CSTEXT,      character large object",
    "TEXT,        character large object",
  })
  void simpleTypeShouldMapToExpectedSql(String typeName, String expectedSql) {
    Column col = new Column("col", ColumnType.getColumnType(typeName.trim()), 0, false);
    assertEquals(expectedSql.trim(), generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("CHAR with length should produce char(n)")
  void charShouldProduceCharWithLength() {
    Column col = new Column("col", ColumnType.CHAR, 10, false);
    assertEquals("char(10)", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("VARCHAR with length should produce varchar(n)")
  void varcharShouldProduceVarcharWithLength() {
    Column col = new Column("col", ColumnType.VARCHAR, 255, false);
    assertEquals("varchar(255)", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("DECIMAL with precision and scale should produce decimal(p,s)")
  void decimalWithPrecisionAndScaleShouldProduceDecimalPrecisionScale() {
    Column col = new Column("col", ColumnType.DECIMAL, 19, 4, false, null, null, null, null, null, null, null);
    assertEquals("decimal(19,4)", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("DECIMAL with no precision or scale should produce decimal")
  void decimalWithNoPrecisionOrScaleShouldProduceBareDecimal() {
    Column col = new Column("col", ColumnType.DECIMAL, 0, 0, false, null, null, null, null, null, null, null);
    assertEquals("decimal", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("BOOLEAN with NATIVE mode should produce boolean")
  void booleanNativeShouldProduceBoolean() {
    Column col = new Column("col", ColumnType.BOOLEAN, 0, false);
    assertEquals("boolean", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("BOOLEAN with YES_NO mode should produce varchar(3)")
  void booleanYesNoShouldProduceVarchar3() {
    H2ColumnTypeGenerator yesNoGenerator = createGenerator(BooleanMode.YES_NO, null);
    Column col = new Column("col", ColumnType.BOOLEAN, 0, false);
    assertEquals("varchar(3)", yesNoGenerator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("BOOLEAN with YN mode should produce char(1)")
  void booleanYnShouldProduceChar1() {
    H2ColumnTypeGenerator ynGenerator = createGenerator(BooleanMode.YN, null);
    Column col = new Column("col", ColumnType.BOOLEAN, 0, false);
    assertEquals("char(1)", ynGenerator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("ENUM should produce enum('value1','value2',...)")
  void enumShouldProduceEnumWithValues() {
    Schema schema = new Schema(null);
    EnumType enumType = new EnumType("Status");
    enumType.addValue(new EnumValue("Active", "ACTIVE"));
    enumType.addValue(new EnumValue("Inactive", "INACTIVE"));
    schema.addEnumType(enumType);
    H2ColumnTypeGenerator enumGenerator = createGenerator(BooleanMode.NATIVE, schema);
    Column col = new Column("col", ColumnType.ENUM, 0, 0, false, null, null, null, null, null, "Status", null);
    assertEquals("enum('ACTIVE','INACTIVE')", enumGenerator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("ARRAY of VARCHAR should produce varchar(n) array")
  void arrayOfVarcharShouldProduceVarcharArray() {
    Column col = new Column("col", ColumnType.ARRAY, 100, 0, false, null, null, null, null, null, null, ColumnType.VARCHAR);
    assertEquals("varchar(100) array", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("ARRAY of INT should produce INT array (default name)")
  void arrayOfIntShouldProduceIntArray() {
    Column col = new Column("col", ColumnType.ARRAY, 0, 0, false, null, null, null, null, null, null, ColumnType.INT);
    assertEquals("INT array", generator.getColumnTypeSql(null, col));
  }

  @Test
  @DisplayName("ARRAY of TEXT should produce character large object array")
  void arrayOfTextShouldProduceCharacterLargeObjectArray() {
    Column col = new Column("col", ColumnType.ARRAY, 0, 0, false, null, null, null, null, null, null, ColumnType.TEXT);
    assertEquals("character large object array", generator.getColumnTypeSql(null, col));
  }

  private H2ColumnTypeGenerator createGenerator(BooleanMode booleanMode, Schema schema) {
    SQLGenerator sqlGen = new SQLGenerator(
        new SQLGeneratorOptions(schema, null, DatabaseType.H2, ForeignKeyMode.RELATIONS,
            booleanMode, OutputMode.ALL)) {
      @Override protected void outputTables() {}
      @Override protected void outputRelations() {}
      @Override protected void outputIndexes() {}
      @Override protected void outputTriggers() {}
      @Override protected void outputFunctions() {}
      @Override protected void outputViews() {}
      @Override protected void outputProcedures() {}
      @Override protected void outputOtherSqlTop() {}
      @Override protected void outputOtherSqlBottom() {}
    };
    return new H2ColumnTypeGenerator(sqlGen);
  }
}
