package com.stano.schema.installer.flyway;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.stano.schema.model.DatabaseType;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("FlywayDatabaseUpgradeLog")
class FlywayDatabaseUpgradeLogTest {

  private Connection conn;
  private FlywayDatabaseUpgradeLog log;

  @BeforeEach
  void setUp() throws SQLException {
    conn =
        DriverManager.getConnection("jdbc:h2:mem:test_" + System.nanoTime() + ";MODE=PostgreSQL");
    log = new FlywayDatabaseUpgradeLog();
  }

  @AfterEach
  void tearDown() {
    if (conn != null) {
      try {
        conn.close();
      } catch (Exception e) {
        // ignore
      }
    }
  }

  @Test
  @DisplayName("start creates databaseupgradelog table if not exists")
  void startCreatesDatabaseupgradelogTableIfNotExists() {
    assertFalse(tableExists("databaseupgradelog"));

    long logId = log.start(DatabaseType.H2, conn, "V1__install.sql");

    assertTrue(tableExists("databaseupgradelog"));
    assertTrue(logId > 0);
  }

  @Test
  @DisplayName("start inserts a row with StartDateTime and ChangeLogName")
  void startInsertsARowWithStartDateTimeAndChangeLogName() {
    long logId = log.start(DatabaseType.H2, conn, "some/path/to/V1__test.sql");

    Map<String, Object> row = getLogRow(logId);
    assertEquals(row.get("ChangeLogName"), "V1__test.sql");
    assertNotNull(row.get("StartDateTime"));
    assertNull(row.get("EndDateTime"));
    assertNull(row.get("Error"));
  }

  @Test
  @DisplayName("finish updates EndDateTime when no error")
  void finishUpdatesEndDateTimeWhenNoError() {
    long logId = log.start(DatabaseType.H2, conn, "V1__test.sql");

    log.finish(conn, (int) logId, null);

    Map<String, Object> row = getLogRow(logId);
    assertNotNull(row.get("EndDateTime"));
    assertNull(row.get("Error"));
  }

  @Test
  @DisplayName("finish updates both EndDateTime and Error when error provided")
  void finishUpdatesBothEndDateTimeAndErrorWhenErrorProvided() {
    long logId = log.start(DatabaseType.H2, conn, "V1__test.sql");

    log.finish(conn, (int) logId, "Something went wrong");

    Map<String, Object> row = getLogRow(logId);
    assertNotNull(row.get("EndDateTime"));
    assertEquals(row.get("Error"), "Something went wrong");
  }

  @Test
  @DisplayName("handles legacy databaseupgradelog table missing ChangeLogName column")
  void handlesLegacyDatabaseupgradelogTableMissingChangeLogNameColumn() {
    try (Statement stmt = conn.createStatement()) {
      stmt.executeUpdate(
          "create table databaseupgradelog (ID integer generated by default as identity (start with"
              + " 1) not null,StartDateTime datetime not null,EndDateTime datetime,constraint"
              + " pk_databaseupgradelog primary key (ID))");
    } catch (Exception e) {
      throw new RuntimeException(e);
    }

    long logId = log.start(DatabaseType.H2, conn, "V1__test.sql");

    assertTrue(logId > 0);
    assertTrue(columnExists("databaseupgradelog", "changelogname"));
  }

  private boolean tableExists(String tableName) {
    try (Statement stmt = conn.createStatement()) {
      try (ResultSet rs = stmt.executeQuery("select * from " + tableName + " limit 1")) {
        return true;
      }
    } catch (Exception e) {
      return false;
    }
  }

  private boolean columnExists(String tableName, String columnName) {
    try {
      try (Statement stmt = conn.createStatement()) {
        stmt.executeQuery("select " + columnName + " from " + tableName + " limit 1");
        return true;
      }
    } catch (Exception e) {
      return false;
    }
  }

  private Map<String, Object> getLogRow(long logId) {
    try (Statement stmt = conn.createStatement()) {
      try (ResultSet rs =
          stmt.executeQuery("select * from databaseupgradelog where ID = " + logId)) {
        if (rs.next()) {
          Map<String, Object> row = new HashMap<>();
          row.put("ID", rs.getInt("ID"));
          row.put("ChangeLogName", rs.getString("ChangeLogName"));
          row.put("StartDateTime", rs.getTimestamp("StartDateTime"));
          row.put("EndDateTime", rs.getTimestamp("EndDateTime"));
          row.put("Error", rs.getString("Error"));
          return row;
        }
      }
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
    return null;
  }
}
