package com.stano.schema.installer.schemacontext;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.stano.schema.model.BooleanMode;
import com.stano.schema.model.ForeignKeyMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("DefaultSchemaContext")
class DefaultSchemaContextTest {

  private Connection conn;
  private DefaultSchemaContext ctx;

  @BeforeEach
  void setUp() throws Exception {
    conn =
        DriverManager.getConnection("jdbc:h2:mem:test_" + System.nanoTime() + ";MODE=PostgreSQL");
    ctx = new DefaultSchemaContext(null, null);
  }

  @AfterEach
  void tearDown() throws Exception {
    if (conn != null) {
      conn.close();
    }
  }

  @Test
  @DisplayName("getBooleanMode returns NATIVE by default")
  void getBooleanModeReturnsNativeByDefault() {
    assertEquals(BooleanMode.NATIVE, ctx.getBooleanMode());
  }

  @Test
  @DisplayName("getForeignKeyMode returns RELATIONS by default")
  void getForeignKeyModeReturnsRelationsByDefault() {
    assertEquals(ForeignKeyMode.RELATIONS, ctx.getForeignKeyMode());
  }

  @Test
  @DisplayName("getPostCreateScriptLocator returns null by default")
  void getPostCreateScriptLocatorReturnsNullByDefault() {
    assertNull(ctx.getPostCreateScriptLocator(conn));
  }

  @Test
  @DisplayName("schemaInstalled is a no-op")
  void schemaInstalledIsNoOp() throws Exception {
    ctx.schemaInstalled(conn);
  }

  @Test
  @DisplayName("schemaIsInstalled returns false when databaseupgradelog table is absent")
  void schemaIsInstalledReturnsFalseWhenTableAbsent() throws Exception {
    assertFalse(ctx.schemaIsInstalled(conn));
  }

  @Test
  @DisplayName("schemaIsInstalled returns true when databaseupgradelog table exists")
  void schemaIsInstalledReturnsTrueWhenTableExists() throws Exception {
    try (Statement stmt = conn.createStatement()) {
      stmt.executeUpdate(
          "create table databaseupgradelog (ID integer generated by default as identity not null, "
              + "StartDateTime timestamp not null, constraint pk_dul primary key (ID))");
    }
    assertTrue(ctx.schemaIsInstalled(conn));
  }
}
