package com.stano.schema.installer.flyway

import com.stano.schema.model.DatabaseType
import spock.lang.Specification

import java.sql.Connection
import java.sql.DriverManager
import java.sql.Statement

class FlywayDatabaseUpgradeLogSpec extends Specification {
  private Connection conn
  private FlywayDatabaseUpgradeLog log

  void setup() {
    conn = DriverManager.getConnection("jdbc:h2:mem:test_${System.nanoTime()};MODE=PostgreSQL")
    log = new FlywayDatabaseUpgradeLog()
  }

  void cleanup() {
    conn?.close()
  }

  def "start creates databaseupgradelog table if not exists"() {
    given: "no databaseupgradelog table"
    def tableExistsBefore = tableExists("databaseupgradelog")

    when: "we call start"
    def logId = log.start(DatabaseType.H2, conn, "V1__install.sql")

    then: "table is created and row inserted"
    tableExists("databaseupgradelog")
    logId > 0
  }

  def "start inserts a row with StartDateTime and ChangeLogName"() {
    when: "we call start"
    def logId = log.start(DatabaseType.H2, conn, "some/path/to/V1__test.sql")

    then: "row exists with correct data"
    def row = getLogRow(logId)
    row.ChangeLogName == "V1__test.sql"
    row.StartDateTime != null
    row.EndDateTime == null
    row.Error == null
  }

  def "finish updates EndDateTime when no error"() {
    given: "a started log entry"
    def logId = log.start(DatabaseType.H2, conn, "V1__test.sql")

    when: "we call finish with null error"
    log.finish(conn, logId, null)

    then: "row is updated with EndDateTime"
    def row = getLogRow(logId)
    row.EndDateTime != null
    row.Error == null
  }

  def "finish updates both EndDateTime and Error when error provided"() {
    given: "a started log entry"
    def logId = log.start(DatabaseType.H2, conn, "V1__test.sql")

    when: "we call finish with an error"
    log.finish(conn, logId, "Something went wrong")

    then: "row is updated with both EndDateTime and Error"
    def row = getLogRow(logId)
    row.EndDateTime != null
    row.Error == "Something went wrong"
  }

  def "handles legacy databaseupgradelog table missing ChangeLogName column"() {
    given: "an old databaseupgradelog table without ChangeLogName"
    try (Statement stmt = conn.createStatement()) {
      stmt.executeUpdate(
        "create table databaseupgradelog (ID integer generated by default as identity (start with 1) not null,StartDateTime datetime not null,EndDateTime datetime,constraint pk_databaseupgradelog primary key (ID))"
      )
    }

    when: "we call start"
    def logId = log.start(DatabaseType.H2, conn, "V1__test.sql")

    then: "ChangeLogName column is added and row inserted"
    logId > 0
    columnExists("databaseupgradelog", "changelogname")
  }

  private boolean tableExists(String tableName) {
    try (Statement stmt = conn.createStatement()) {
      try (def rs = stmt.executeQuery("select * from $tableName limit 1")) {
        return true
      }
    }
    catch (Exception e) {
      return false
    }
  }

  private boolean columnExists(String tableName, String columnName) {
    try {
      try (Statement stmt = conn.createStatement()) {
        stmt.executeQuery("select $columnName from $tableName limit 1")
        return true
      }
    }
    catch (Exception e) {
      return false
    }
  }

  private Map getLogRow(int logId) {
    try (Statement stmt = conn.createStatement()) {
      try (def rs = stmt.executeQuery("select * from databaseupgradelog where ID = $logId")) {
        if (rs.next()) {
          return [
            ID: rs.getInt("ID"),
            ChangeLogName: rs.getString("ChangeLogName"),
            StartDateTime: rs.getTimestamp("StartDateTime"),
            EndDateTime: rs.getTimestamp("EndDateTime"),
            Error: rs.getString("Error")
          ]
        }
      }
    }
    return null
  }
}
